### ISSUE TITLE
Why do you set values of dist to 0x3f, isn't that too small?

### ISSUE THREAD

**Issue by Kostekgol** [Jonathan-Uy/CSES-Solutions#3]

**Comment by Jonathan-Uy** [comment]
For future reference, this question was about the use of `memset`, for example in [Shortest Routes I](https://github.com/Jonathan-Uy/CSES-Solutions/blob/main/Graph%20Algorithms/Shortest%20Routes%20I.cpp).

`memset(dist, 0x3f, sizeof(dist))` writes by bytes. Every byte in the array `dist` is set to `0x3f`, and since long longs have eight bytes, then each value in the array is actually set to `0x3f3f3f3f3f3f3f3f`, which is large enough to use as infinity.
