### ISSUE TITLE
Time Complexity

### ISSUE THREAD

**Issue by Kostekgol** [Jonathan-Uy/CSES-Solutions#7]
https://github.com/Jonathan-Uy/CSES-Solutions/blob/3d176342a6f0fc77cb03f92fe7e6ce811dd6e9bf/Graph%20Algorithms/Giant%20Pizza.cpp#L74
![image](https://user-images.githubusercontent.com/94232164/191557992-a5682a4a-52fe-4449-86fa-59d082359787.png)
It seems to me that these 2 loops can possibly run in O(n*m). I know that it can't be the case, bc of limit, what's the complexity of those?

**Comment by Jonathan-Uy** [comment]
The `if` statement on Line 76 is run as many times as there are edges in the graph. This is because `u` will be the start node of an edge, `v` will be the end node, and no edge will be counted twice (in this question, the graph is directed). So, the two for-loops have $O(\max(N, M))$ time complexity.
